### ISSUE TITLE
Custom plugin GUIs can't be closed when using Carla in Tracktion

### ISSUE THREAD

**Issue by SpotlightKid** [falkTX/Carla#170]
Not sure whether this is a Tracktion or Carla bug.

In Carla standalone I can load plugins and unload plugins just fine and open their custom GUI (either through the right-click menu or the "GUI" button) and close their GUI window again.

Whoever, when I load Carla (Patchbay, PatchbayFx, Rack, RackFX, doesn't matter) as a VST plugin in Tracktion and then load a plugin in Carla (e.g. Calf Phaser, but any plugin will show the same problem), I can open the custom GUI, but when I try to close it by clicking on the close button of the window decoration, the window does not close, only the light blue frame around the "GUI" button in the plugin slot in Carla disappears. When I click that button, the plugin window disappears but the reappears immediately again, but is then unresponsive (but still processes Audio/MIDI). I can then only remove the plugin window by killing it and with it Carla and Tracktion.

I just re-checked this with newest Tracktion (5.4.2) and Carla compiled from git as of now (2014-02-03 19:00 CET).

**Comment by falkTX** [comment]
Can you recheck this please?
Thanks

**Comment by SpotlightKid** [comment]
Just recompiled Carla from current git and tried again. I'm sorry to say that the situation hasn't improved.

Tracktion (5.4.2) loads the Carla VST plugin fine (Carla/Patchbay/FX, doesn't matter), but the plugin GUI shows without the window decoration (see screenshot 1) Tracktion normally adds (see attached screenshot 3).

You can move the plugin window, when you click-and-drag in the upper part of the window, where the menu is displayed, but otherwise the the GUI is unresponsive, except that the buttons (e.g. "Add Plugin") are highlighted when you hover over them with the mouse (see screenshot 2), but clicking them or the menu doesn't do anything.

Also note that the GUI has a black border at the bottom. To me it seems that there is a wrong horizontal offset somewhere and maybe a mismatch between the position graphics of the GUI and where the GUI event handlers think everything is.
![carla-tracktion_issue-170-01](https://cloud.githubusercontent.com/assets/5719151/5877603/f34b9086-a320-11e4-801d-cfa6b82a0b10.png)
![carla-tracktion_issue-170-02](https://cloud.githubusercontent.com/assets/5719151/5877604/f34efaaa-a320-11e4-957d-a5d81ce4fd9f.png)
![carla-tracktion_issue-170-03](https://cloud.githubusercontent.com/assets/5719151/5877605/f34f45a0-a320-11e4-988f-9ac5334c3c20.png)

**Comment by falkTX** [comment]
tbh this seems like a tracktion bug.

is it only carla that has this issue?
Do other plugins have it as well?

I guess I'll install tracktion again and test it myself too...

**Comment by SpotlightKid** [comment]
Other plugins have display issues in Tracktion on Linux as well, but they are generally responsive.

For example, sometimes a plugin windows opens, but has only a size of 30 pixels wide. You can only resize it by selecting "change size" from the context menu of the window switcher in the panel (I'm using Xfce4 here). The window can be resized to be bigger than the actual plugin GUI size.

I've experienced that with several different plugins.

Would be great if you could check, whether Tracktion gives some wrong info to the plugin or if it interprets data from the plugins incorrectly. Then maybe a better bug report can be filed with the Tracktion developers.

**Comment by falkTX** [comment]
This should be fixed now in latest carla-git.
Please confirm so I can close this bug.

**Comment by falkTX** [comment]
We might need to wait for the next Tracktion update.

I tested with the example juce host and it works correctly:
![scr033](https://cloud.githubusercontent.com/assets/1334853/6126061/5c0a708c-b114-11e4-9fc8-8175220f15a0.png)

So the next tracktion update should have this fixed.

**Comment by falkTX** [comment]
actually, no, nevermind my previous post.
(I was thinking of something else)

waiting for the window to be created is not enough.
tracktion still messes up the window the 2nd time it's created...

**Comment by SpotlightKid** [comment]
Yeah, and we're back to the original problem. Custom Plugin GUI opened from within Carla (as a plugin) cannot be closed. I'll clamour for a new Tracktion Linux release soon on the Tracktion forum

**Comment by falkTX** [comment]
The new release will do nothing, I was thinking of something else when I said that before, sorry.

I think I know what the issue is, I'll try something soon.

**Comment by falkTX** [comment]
The latest commits should have made carla working better in Tracktion, possibly fixing this bug too.
(at the expense of 1/4 freeze when showing the UI).

Please test.

**Comment by SpotlightKid** [comment]
Nope, the original bug is still there (tested a new Carla package compiled from Git today) against Tracktion 6. Overall Tracktion 6 on Linux doesn't seem to have brought much improvements in the VST plugin display department. The sad thing is, that plugins written with Juce seem to exhibit the most problems.

**Comment by falkTX** [comment]
Please try again with the latest version, 25% chance it fixes this.

The real fix (disabling setting transient hint) is yet to come.

**Comment by SpotlightKid** [comment]
Finally, it seems to work. Yeay! Tested with the latest Tracktion Version 5.4.3 (Built: 14 January 2015) (64-bit) and Tracktion Version 6.0.18 (Built: 22 February 2015) (64-bit) and Carla built from Git 2850.3509edb.

Tracktion seems to have improved VST GUI issues under Linux generally, I am seeing less GUI issues with other VST plugins (e.g. from TAL or dbrowaudio), but sometimes the plugin window title bar is still missing and there is a black horizontal bar at the bottom instead. I didn't encounter this with Carla in my latests tests thoug

**Comment by falkTX** [comment]
The reason carla always works is because (when it detects Tracktion) it delays the UI opening by a 1 second, usually giving enough time for X11 to actually create the window.

Having debugging this was very informative for Juce/Tracktion, I reported the bug upstream and hopefully I'll have a fix for them soon.

**Comment by spsx** [comment]
Strangely enough, I cannot get this to work on Tracktion 5.4.3, with the same problems as mentioned by Spotlightkid earlier. I'm running Carla 1.9.6 (the latest version in the KXstudio repos). However, I'm not familiar with Github, and don't know how to check if my version is older than the 2850.3509edb release tested by Spotlightkid.

Also, I'm confused as to why this is still marked as a bug, since it appears to have been fixed in the 2850.3509edb release.

**Comment by falkTX** [comment]
Update tracktion, this was already fixed a while ago.

**Comment by spsx** [comment]
5.4.3 is already the latest revision of version 5, which I'm using. This is unless you are referring to version 6 (which is a paid upgrade from 5).

**Comment by falkTX** [comment]
Yes, I'm speaking about version >= 6.

you can revert this commit which adds a tracktion specific workaround: https://github.com/falkTX/Carla/commit/d9b781951c27635f0a7ff17b7d012d3c905bb5cb

**Comment by falkTX** [comment]
This issue should no longer happen in tracktion 7, which was released as free update a few weeks ago.
Assuming fixed, if it is not the case, please repopen

**Comment by mikobuntu** [comment]
I think this is not fixed correctly ( at least using the very latest version of Tracktion/Waveform-9.3.2 )
On opening Carla the host window wrapper does correctly display Carla, but as soon as the mouse pointer hovers over the actual contained Carla window then it displays similar to Spotlightkid's Images from above posts, i.e no window decoration.

Using Carla version 1.9.9 (2.0-beta7)
  Python version: 3.5.2
  Qt version:     5.5.1
  PyQt version:   5.5.1
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources

![carla_waveform_glitch](https://user-images.githubusercontent.com/335217/45113424-392cdf00-b142-11e8-9081-83d96fa575fe.gif)

**Comment by falkTX** [comment]
Thanks for the report, but that issue is a different one.
I will remove the embed carla version and replace it with a button to open the actual full interface, at some later point.
(though I can try to reproduce the issue and fix it perhaps)

What I wonder here if regarding this specific bug title, of plugin UIs being left visible when carla is closed.
Confirmation on that would be welcome.

**Comment by mikobuntu** [comment]
@falkTX Ah I just zoomed through the post quickly sorry. Great hopefully the button fixes this issue or if you can reproduce it and fix it , even better. 
I will test the bug in question here and report back in a few minutes, thanks :)

**Comment by mikobuntu** [comment]
@falkTX Ok I can confirm that everything in respect to windows closing is working as normal, so I believe the original Bug can be marked as fixed.
Would you like me to copy the Bug I reported above to a new issue or can you handle that? 
thanks :)

**Comment by falkTX** [comment]
Yes, please open a new issue for that one.
Thanks!
